---

- name: create elb
  ec2_elb_lb:
    name: sampleElb
    state: present
    region: eu-west-1
    aws_access_key: "{{lookup('env', 'AWS_ACCESS_KEY_ID')}}"
    aws_secret_key: "{{lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
    zones:
      - eu-west-1a
      - eu-west-1b
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
      # - protocol: https
      #   load_balancer_port: 443
      #   instance_protocol: http
      #   instance_port: 80
        #ssl_certificate_id: 'arn:aws:iam::123456789:server-certificate/halberom'
  register: elb

