---

 - name: "Create {{ user_group }} group"
   group: >
     name={{ user_group }}
     state="present"

 - name: "Create {{ user_name }} user"
   user: >
     name={{ user_name}}
     group={{ user_group }}
     home="/home/{{ user_name }}"
     createhome=yes
     move_home=yes
     comment="{{ user_name }} user"
     shell="/bin/bash"
     state="present"  

 - name: "Create directory /etc/sudoers.d"
   file: >
     path="/etc/sudoers.d"
     state="directory"
     owner="root"
     group="root"
     mode=0755

 - name: "Remove requiretty in /etc/sudoers"
   lineinfile: >
     dest="/etc/sudoers"
     regexp="^\s*Defaults\s*requiretty"
     state="absent"
     validate='/usr/sbin/visudo -cf %s'  

 - name: "Grant sudo permission (full access)"
   template: >
     src="sudoers_file.j2"
     dest="/etc/sudoers.d/{{ user_name }}"
     owner="root"
     group="root"
     mode="0400"  

 - name: "Ensure home directory ownership is correct"
   file: >
     path="/home/{{ user_name }}/"
     owner="{{ user_name }}"
     group="{{ user_group }}"
     state="directory"  

 - name: "Create .ssh directory"
   file: >
     path="/home/{{ user_name }}/.ssh"
     owner="{{ user_name }}"
     group="{{ user_group }}"
     mode="0700"
     state="directory"  

 - name: "Setup key based ssh login"
   copy: >
     src="authorized_keys"
     dest="/home/{{ user_name }}/.ssh/authorized_keys1"
     owner="{{ user_name }}"
     group="{{ user_group }}"
     mode="0600"

 - name: "Append contents form authorized_keys1 to authorized_keys"
   shell: "cd /home/{{ user_name }}/.ssh && cat authorized_keys1 >> authorized_keys"

 - name: "Setup {{ user_name }} public key"
   copy: >
     src="id_rsa.pub"
     dest="/home/{{ user_name }}/.ssh/id_rsa.pub"
     owner="{{ user_name }}"
     group="{{ user_group }}"
     mode="0600"

 - name: "Setup {{ user_name }} private key"
   copy: >
     src="id_rsa"
     dest="/home/{{ user_name }}/.ssh/id_rsa"
     owner="{{ user_name }}"
     group="{{ user_group }}"
     mode="0600"

 - name: "Setup {{ user_name }} ssh config"
   copy: >
     src="config"
     dest="/home/{{ user_name }}/.ssh/config"
     owner="{{ user_name }}"
     group="{{ user_group }}"
     mode="0600"